"""Add Google refresh token to User model

Revision ID: 07490c6d8b1a
Revises: 046fb59208e2
Create Date: 2024-10-17 22:09:45.365187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07490c6d8b1a'
down_revision = '046fb59208e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_refresh_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_refresh_token')

    # ### end Alembic commands ###
