"""Add feedback field in User model

Revision ID: 5c043cd9ec8b
Revises: 07490c6d8b1a
Create Date: 2024-10-18 22:46:49.078720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c043cd9ec8b'
down_revision = '07490c6d8b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
